### ISSUE TITLE
literal with .lang set shoudl have datatype rdf:langString

### ISSUE THREAD

**Issue by elf-pavlik** [linkeddata/rdflib.js#107]
> if and only if the datatype IRI is http://www.w3.org/1999/02/22-rdf-syntax-ns#langString, a non-empty language tag as defined by [BCP47]. The language tag MUST be well-formed according to section 2.2.9 of [BCP47].

https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal

see also: https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#literal-extends-term

**Comment by TommasoBianchi** [comment]
Hi all, I am using rdflib to build a library to parse [SKOS](https://www.w3.org/TR/skos-reference/#notes) documents in RDF/XML format, and I am incurring in the same issue as above.
The following XML string

```xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:skos="http://www.w3.org/2004/02/skos/core#">
  <skos:Concept rdf:about="http://lod.nal.usda.gov/nalt/218714">
    <skos:prefLabel rdf:datatype="http://www.w3.org/1999/02/22-rdf-syntax-ns#langString" xml:lang="en">My label</skos:prefLabel>
  </skos:Concept>
</rdf:RDF>
```

generates, after being parsed, the following statements in the store (note how in the second one there is the langString datatype but no lang)

```js
[
  Statement {
    subject: NamedNode {
      termType: 'NamedNode',
      value: 'http://lod.nal.usda.gov/nalt/218714'
    },
    predicate: NamedNode {
      termType: 'NamedNode',
      value: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'
    },
    object: NamedNode {
      termType: 'NamedNode',
      value: 'http://www.w3.org/2004/02/skos/core#Concept'
    },
    why: NamedNode { termType: 'NamedNode', value: 'a:a' }
  },
  Statement {
    subject: NamedNode {
      termType: 'NamedNode',
      value: 'http://lod.nal.usda.gov/nalt/218714'
    },
    predicate: NamedNode {
      termType: 'NamedNode',
      value: 'http://www.w3.org/2004/02/skos/core#prefLabel'
    },
    object: Literal {
      termType: 'Literal',
      value: 'My label',
      datatype: NamedNode {
        termType: "NamedNode",
        value: "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
      }
    },
    why: NamedNode { termType: 'NamedNode', value: 'a:a' }
  }
]
```

I think that to solve the problem it might be sufficient to change the function `addLiteral` in `rdfxmlparser.js` to add an additional check, like this

```js
if (this.parent.datatype && this.parent.datatype !== 'http://www.w3.org/1999/02/22-rdf-syntax-ns#langString') {
  this.node = this.store.literal(value, '', this.store.sym(this.parent.datatype));
} else {
  this.node = this.store.literal(value, this.lang);
}
```

If you think that the fix is good I can open a PR, otherwise I'm up for a discussion on how to fix.
