### ISSUE TITLE
[Q] Factory methods for RDF primitives -- formula instance vs. $rdf

### ISSUE THREAD

**Issue by ckristo** [linkeddata/rdflib.js#114]
Hi,

I'm currently writing a summary on how to use rdflib.js. I encountered that some factory methods for creating RDF primitives (like resources, statements) are defined on `$rdf` as well as on `Formula`, others aren't. Is there a particular reason why `$rdf.sym()` and `$rdf.st()` e.g. are defined, while `$rdf.bnode()` or `$rdf.literal()` aren't?

BR, Chris

**Comment by adynata** [comment]
@ckristo do you have your in-progress summary of how to use the library up anywhere? I'm in the midst of a project using the library and would love to have access to more resources describing how to use it.

**Comment by ckristo** [comment]
@adynata sure, it can be found here: https://bitbucket.org/ckristo/sw-examples/src/HEAD/main.pdf -- chapter 3.8. Futhermore, samples on how to use rdflib.js can be found here: https://bitbucket.org/ckristo/sw-examples/src/HEAD/examples/js/rdflib.js-example

**Comment by dmitrizagidulin** [comment]
@ckristo - this is great stuff! Thanks!

**Comment by timbl** [comment]
@ckristo thank you so much for taking this on!
To answer the original question, there is no good reason why things are different. Shortcuts have been added from just realizing that they will make code more concise, hence $rdf.sym rather than $rdf.symbol for new $rdf.Symbol .    

We are very happy to add (or have pull requests for) things that are missing.


As "symbol" is rather out of fashion, we may add for example $rdf.node(uri) where $rdf.node() would give a bnode

**Comment by adynata** [comment]
@ckristo That is a huge help! Thank you so much.

**Comment by ckristo** [comment]
@dmitrizagidulin, @timbl, @adynata: thanks, glad you like it. Maybe some parts of it could serve as start for creating some kind of documentation for rdflib.js?

**Comment by dmitrizagidulin** [comment]
@ckristo re serving as a start for documentation for rdflib.js -- absolutely, we'll try to merge in what we can.
