### ISSUE TITLE
Issue with external libraries like solid-auth-client

### ISSUE THREAD

**Issue by jairo-campos-JD** [linkeddata/rdflib.js#289]
On fetch.js we have a require call for solid-auth-client but on webpack config is like external, that means that should works if we already import solid-auth-client in our projects, but in this case is not working because will point to internal dependencies.

Here is the issue: 

const auth = require('solid-auth-client')
const fetch = auth ? auth.fetch : (a, b) => window.fetch(a, b)

This works fine on projects where you copy externals script like rdf and solid-auth-client in the bundle but if we want to create a library these libraries should be external to reduce library size and do not have duplicate code.

We can fix it checking if we have solid-auth-client in the context.

const auth = require('solid-auth-client')
const fetch = auth ? auth.fetch : window && solid && solid.auth ? solid.auth.fetch : (a, b) => window.fetch(a, b)

cc: @RubenVerborgh

**Comment by RubenVerborgh** [comment]
Knowledge about the packaging of a library should not be present in the code. So actually, the current code is already incorrect in that regard, because it checks whether `auth` is falsy, which can only happen in webpack circumstances.

So we will need to find a different proposed solution.

> On fetch.js we have a require call for solid-auth-client but on webpack config is like external

That webpack config is _only_ run when building rdflib.as a standalone library, i.e., when you use `rdflib.min.js`. It will not be used when you use `require`.

When you have a `require` call for `solid-auth-client`, that `require` call will be resolved according to the rules that you specify in your own `webpack.config` file. So whatever goes wrong there should be fixed in your `webpack.config`. Happy to have a look at the concrete project.

> if we want to create a library these libraries should be external to reduce library size and do not have duplicate code

Why would there be duplicate code?

I'm assuming then that you have a copy of `rdflib.min.js` _and_ also a `require` version. It is not advised to combine both approaches; either you build with webpack and include, or you use the individual scripts.

What you probably want, is to build with webpack, and then expose `rdflib` as a global from within there.

**Comment by jairo-campos-JD** [comment]
Hi @RubenVerborgh 

Thank you for you answers, like you said I fixed adding alias on the webpack like 'solid-auth-client': 'solid' so when this go to require solid-auth-client will get the solid context that should be already import on project.

Thanks,

**Comment by RubenVerborgh** [comment]
> So actually, the current code is already incorrect in that regard, because it checks whether `auth` is falsy, which can only happen in webpack circumstances.

Addressed in 2421d66b4d3d579feaa74f43fd33c1bfc347321c.
