### ISSUE TITLE
confirm that namespaces link is now correct

### ISSUE THREAD

**Issue by TallTed** [linkeddata/rdflib.js#481]
Re: [Line 95 of webapp-intro.html](https://github.com/linkeddata/rdflib.js/blob/5506be534cf8fc29882e02ec011f2524bf43f6c9/Documentation/webapp-intro.html#L95)

In #321, on 2019-07-21, I was told by @TylerRick that `https://github.com/solid/solid-ui/blob/master/src/ns.js` [should be replaced by `https://github.com/solid/solid-namespace/blob/master/index.js`](https://github.com/linkeddata/rdflib.js/pull/321/files#r307943944).  Today, #321 was merged by @jeff-zucker, and I was again asked to make this URL change (which couldn't be done within #321, due to inadvertent branch deletion) with a new PR.

However, while #321 languished, @janschill replaced `https://github.com/solid/solid-ui/blob/master/src/ns.js` [with `https://github.com/solid/solid-namespace`](https://github.com/linkeddata/rdflib.js/commit/77292a87cd9aa77aa2c56c9fb73cf002be75bf41), which is there now.

I don't know which of `https://github.com/solid/solid-namespace` or `https://github.com/solid/solid-namespace/blob/master/index.js` is correct and should persist.  I'm sure someone reading this will know, and will either close this with "it's correct now" or tell me to make (or will make their own) PR to change it to the other.

**Comment by jeff-zucker** [comment]
Thanks @TallTed - the one Jan used is probably better, so nothing needs to be done. The only reason I asked you to make the PR on the other one instead of doing it myself is that I'm pretty sure that if I made the PR, I couldn't also merge the PR, and thought it would be faster for you to do it and me to merge it than for me to do it and wait for someone else to merge it.
