### ISSUE TITLE
Parsing RDF/XML, N-Triples or Turtle

### ISSUE THREAD

**Issue by lmatteis** [linkeddata/rdflib.js#57]
Hi,

I'm looking for a basic example on how to parse RDF content and retrieve the triples it contains. I'm using Node.js. Something like:

    rdflib.parse('', function(triples) {
        for(var i in triples)
            console.log(triples[i].subject + triples[i].predicate + triples[i].object)
    })

**Comment by redaktor** [comment]
Hi @lmatteis -
exactly the same here. 
There might be an internal method to load the content and this is 'inofficial'.
However I'll share what I sticked together

```javascript
// YOUR n3 URI ...
var reqUri = '';

var rdflib = require('rdflib');
var request = require('request');
var fs = require('fs');

request({
    url: reqUri,
    headers: {
		'accept-encoding': 'utf-8',
        'content-type': 'text/n3'
    }
}, function(err, res, body) {
	if (err) {
		return err;
	} else if (res.statusCode == 200) {
		var graph = new rdflib.IndexedFormula();
		var rawData = rdflib.parse(body, graph, reqUri, contentType);
		
		// the graph should contain the triplets ...
		// console.log(graph);

		// convert to rdf/xml
		var xmlData = rdflib.serialize(rawData, graph, reqUri, 'application/rdf+xml');
		// do something with xmlData ...
		// fs.writeFileSync('./TEST.xml', xmlData);
	}
});
```

**Comment by danbri** [comment]
This script as bin/rdfxml works for me:

    #!/usr/bin/env python
    import sys
    from rdflib import Graph
    if __name__ == '__main__':
            g = Graph()
            p = Graph()
            u = str(sys.argv[1])
            print "URL: ",u
            g.parse(u, format='xml', pgraph=p)
            print "# errors: "
            print p.serialize(format="nt")

            print "# data: "
            print g.serialize(format="nt")

Via http://rdflib.readthedocs.org/en/latest/intro_to_parsing.html which reveals that (RDF/)XML is the default and that its short name in code seems to be 'xml'.

**Comment by redaktor** [comment]
@danbri this is python code, but the question was for node.js (javascript) (?)

**Comment by danbri** [comment]
Yeah sorry, I deleted my comment already! I just saw the name 'rdflib', which is more widely known as a Python toolkit.

**Comment by redaktor** [comment]
@danbri You're welcome. 
> It is more widely known as a Python toolkit. 

That's right - but I am thankful that the innovators value the popularity and interoperability of javascript now as well ;)

**Comment by danbri** [comment]
Yeah. It would be great to have something in pure js that approximated any23.apache.org as a common way to extract triples regardless of whether it was rdfxml/rdfa/microdata/json-ld/turtle/etc/etc...

**Comment by redaktor** [comment]
@danbri 
1st: https://github.com/linkeddata/node-ldp-httpd (also by linkeddata) sounds promising.
It seems the microdata and json-ld part is not implemented in rdflib.js yet...

And I would expect that .js people would prefer JSON.
Now that's fun because I think we interacted the last time here:
https://groups.google.com/forum/#!topic/json-schema/3cokUTK9elw
[ I am Sebastian, but you did not rerespond to Geraint either ]
However:
The 'transitioning process' you described above for would make totally sense for me – with one additional step:
We can translate the data part to JSON, but we can't translate the schema part to JSON yet.
Why not?
RDFS and XML Schema and OWL are already similar to JSON Schema Internet draft 4 (including hyperschema) and I believe that draft 5 should fill the gaps (just 2 cents of a noob).
However: I recently started to write this (experimental): https://github.com/redaktor/owl2jsonschema.js

**Comment by timbl** [comment]
@danbri, @redaktor, for RDF/a there is a plot to include the green-turtle code. See Issue #20.      JSON/LD  I added as Issue #59.  You ask for  rdfxml/rdfa/microdata/json-ld/turtle/etc/etc --  microdata and etc are a less well-defined question, but if you can define it or point to reference implementation .. Pull requests welcomed!    Agree it would be nice for rdflib.js to have a good set of all the usual suspects.

**Comment by redaktor** [comment]
:+1: 
> microdata and etc are a 
>
>> less well-defined question,
>
> but if you can define it or point to reference implementation ..

agreed - 
@danbri the same for (the big players') "schema.org" ;)

**Comment by martinmr** [comment]
The parse method (in web.js) includes asynchronous and synchronous support for parsing XML, Turtle, and N3. It needs some documentation (much like the rest of the library) and I hope to add it soon.
