### ISSUE TITLE
add @context to jsonld serialization

### ISSUE THREAD

**Issue by bourgeoa** [linkeddata/rdflib.js#591]
Actually the serialize display of jsonld is not easily readable by humans.
The idea is to add a `@context` that will includes the equivalent to turtle `@prefix.`

**Comment by TallTed** [comment]
@bourgeoa -- Please revisit the title and initial comment on this issue, and code fence each instance of `@context` and `@Prefix` by wrapping them in backticks (like ``` `@context` ``` and ``` `@Prefix` ```), so that those GitHub users don't get pinged on every update to this issue which they are not participating in of their own volition.

**Comment by bourgeoa** [comment]
Thanks.
